// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:54db75fc-8803-4215-9330-68cce4a0574f',
    'aws_cognito_region': 'us-east-2',
    'aws_mobile_analytics_app_id': '899b1e5a1e814ce18a006eb147934daf',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'd039a359-65dd-4b01-9f89-87eabd7eae2e',
    'aws_project_name': 'dualslalom',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'dualslalom-mobilehub-741863180',
}

export default awsmobile;
