// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://arngfxlfmfg6ncabtz7z5hf5ha.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fdbpjo3wwrg77k4kv3oxpuerxi",
    "aws_content_delivery_bucket": "uallalomracketre-20190416194323-hostingbucket-dualslalom",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://uallalomracketre-20190416194323-hostingbucket-dualslalom.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
